---
- name: Setting up Ubuntu nodes for Kubernetes
  hosts: kubernetes_nodes
  become: true
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - kubelet
      - kubeadm
      - kubectl
  tasks:

  - name: Remove legacy Kubernetes APT sources
    file:
      path: /etc/apt/sources.list.d/kubernetes.list
      state: absent

  - name: Ensure keyring directory exists
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Add Kubernetes community GPG key
    shell: |
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | \
        gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    args:
      creates: /etc/apt/keyrings/kubernetes-archive-keyring.gpg

  - name: Add Kubernetes community APT repo
    copy:
      dest: /etc/apt/sources.list.d/kubernetes.list
      content: |
        deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
      mode: '0644'

  - name: Updating apt cache
    apt:
      update_cache: yes
      cache_valid_time: 3600
      force_apt_get: yes

  - name: Installing required Kubernetes packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop: "{{ packages }}"

  - name: Hold Kubernetes packages from being updated automatically
    apt:
      name: "{{ item }}"
      state: present
      mark_hold: yes
    loop:
      - kubelet
      - kubeadm
      - kubectl
